# Generated by Django 2.2.5 on 2019-11-30 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30)),
                ('category', models.CharField(choices=[('TECHNOLOGY', 'Technology'), ('MUSIC & ENTERTAINMENT', 'Music & Entertainment'), ('FOOD', 'Food'), ('DANCE', 'Dance'), ('OTHERS', 'Others')], default='MUSIC', max_length=25)),
                ('details', models.TextField(max_length=500)),
                ('venue', models.CharField(max_length=50)),
                ('date', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('time', models.TimeField(help_text='Please use the following format: <em>HH:MM:SS<em>')),
                ('is_archive', models.BooleanField(default=False)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
